### PR TITLE
Impl: Defined entities, resolves #39.

### LINKED ISSUE #37: Add app-routing to project

### LINKED ISSUE #39: Define entities
Project, Task and Comment classes need to be defined.

### LINKED ISSUE #40: Add comment widget to TaskDetailsScreen
Title says all.

### PR DESCRIPTION
**Pull request by espenotlo**
Impl: Added app-routing to existing screens, resolves #37.
Impl: TaskDetailsScreen -> Added comment widget, resolves #40.

### CODE REVIEW

**Comment by espenotlo** [comment]
This PR is a mouthful, apologies!
Biggest changes are the conversion of Widgets to use the newly created entities, as well as the example data.
Also, there now is app routing from "sign in with google" to the other existing screens.
Everything has been tested by myself.

**Review by janitaroyseth — CHANGES_REQUESTED** [review]
### Models
The model classes is missing documentation (😠😡🤬), also models is the preferred named for the folder in this case, not entities. Seeing how we will eventually store data in firebase, perhaps there should be a tags model so we don't store a widget but only the necessary text and hex color information about the tag, and then convert it from the model information to the tag widget. But other than that it looks great!

### Example data
Dart does not use camelcase for naming folders and files, so instead of ``exampleData`` the folder should be ``example_data``, and for the dart file ``exampleData.dart`` should be ``example_data.dart``. 

### Routing
In the ``MaterialApp`` in ``main.dart`` there is a field which is called ``routes`` where we can set a map of named routes for each screen (like approuting in a js framework), and with that also create a `static const String routeName = "/routeNameExample"` for each screen. This way the pushing of screens won't all have to use ``Navigator.push(context, MaterialPageRoute(builder: (context) => ExampleScreen()));`` and can instead use ``Navigator.of(context).pushNamed(ExampleScreen.routeName);`` which makes it less bulky and more easier to read, in my opinion at least. This could've and should've been made clear in the issue, my apologies 😇. It is also possible to send arguments when pushing screens ``Navigator.of(context).pushNamed(ExampleScreen.routeName, arguments: argument);`` instead of having them receive data from the constructors.

good work!

**Comment by espenotlo** [comment]
_Limitations_
_Although named routes can handle deep links, the behavior is always the same and can’t be customized. When a new deep link is received by the platform, Flutter pushes a new Route onto the Navigator regardless where the user currently is._

_Flutter also doesn’t support the browser forward button for applications using named routes. For these reasons, we don’t recommend using named routes in most applications._
From [docs.flutter.dev](https://docs.flutter.dev/development/ui/navigation).

Because of this, I believe that although named routes would be a more lightweight, clear way to implement it; It wouldn't necessarily be the most correct way. I still believe navigator to be the best method of navigation. We can discuss changing this in the next group meeting. :)

**Review by janitaroyseth — COMMENTED** [review]
New changes look good, but we'll have to discuss the routing and agree on that before this pull request is approved :)

**Review by pr0xity — APPROVED** [review]
image

image

**Review by janitaroyseth — APPROVED** [review]
ver cooly

**Pull request merged**
